# Generated by Django 5.2.5 on 2025-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_alter_user_colours_alter_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
