# Generated by Django 5.2.5 on 2025-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_remove_user_age_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
